config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root 'jobs#index'

  namespace :admin do
    resources :jobs
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/hob.rb
class Hob < ApplicationRecord
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs

  def admin?
    is_admin
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/flash_helper.rb
module FlashHelper
	def convert(key)
		case key
		when "alert"
			"danger"
		when "notice"
			"success"
		when "warning"
			"warning" 
		end
	end
end

app/helpers/flashes_heler.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/flashes_help.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcme_helper.rb
module WelcmeHelper
end

app/views/admin/index.html.erb
<div class="col-md-12">
  <div class="pull-right">
    <%= link_to("新增职缺", new_admin_job_path, :class => "btn btn-primary")%>
  </div>

  <br><br>

  <table class="table table-striped">
    <thead>
    <tr>
      <td>#</td>
      <td>职位</td>
      <td>修改|删除</td>
      <td>创建时间</td>
    </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
      <tr>
        <td>#</td>
        <td><%= link_to(job.title, admin_job_path(job)) %></td>
        <td>
          <%= link_to("Edit", edit_admin_job_path(job)%> |
          <%= link_to("Delete", admin_job_path(job), :method => :delete, :data => {:confirm => "Are you sure?"})%>
        </td>
        <td>
          <%= job.created_at %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/commom/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/commom/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登入", '#') %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/common/_flahses.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_flash.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key)%>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_flashesh.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footbar.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by yourname

    </p>
</footer>

app/views/common/_footer.heml.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by tuna

    </p>
</footer>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 Job-Listing
    <br>Design by
    <a href="" target=_new>xdite</a>
  </p>
</footer>

app/views/common/_footer_html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_form.html.erb
<%= simple_form_for @group do |f| %>
 <div class="form-group">
   <%= f.input :title, input_html: { class: "form-control"} %>
   <%= f.input :description, input_html: { class: "form-control"} %>
 </div>

 <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..."} %>
 <% end %>

app/views/common/_menudivider.html.erb
<div class="dropdown clearfix pull-right">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown"
  aria-haspopup="true" aria-expanded="true">
  排序
  <span class="caret"></span>
</button>
<ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
  <li>
    <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
  </li>
  <li>
    <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>
  </li>
  <li>
    <%= link_to("按照发表时间排序", jobs_path) %>
  </li>
</ul>
</div>

<table>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Job-Listing</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-exmaple-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if !current_user %>
            <li><%= link_to("注册", new_user_registration_path) %> </li>
            <li><%= link_to("登入", new_user_session_path) %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Hi!, <%= current_user.email %>
                  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                <% end %>
                  <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
              </ul>
            </li>
          <% end %>
        </li>
      </ul>
    </div>

  </div>

</nav>

app/views/common/_navbar_html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登入", '#') %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/common/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
    <li class="active"><%= link_to("Admin Panel", admin_jobs_path ) %> </li>
    <li class="active"><%= link_to("User Panel", jobs_path ) %> </li>

 </ul>

app/views/common/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
    <%= render "common/footer"%>
  </body>
</html>