config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root 'jobs#index'

  namespace :admin do
    resources :jobs
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/hob.rb
class Hob < ApplicationRecord
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs

  def admin?
    is_admin
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "Destroy success"
  end

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
  @job = Job.find(params[:id])
end

def update
  @job = Job.find(params[:id])
  if @job.update(job_params)
    redirect_to jobs_path
  else
    render :edit
  end
end

def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/falshes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/falshes_hepler.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/flash_helper.rb
module FlashHelper
	def convert(key)
		case key
		when "alert"
			"danger"
		when "notice"
			"success"
		when "warning"
			"warning" 
		end
	end
end

app/helpers/flashes_heler.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/flashes_help.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcme_helper.rb
module WelcmeHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/_job_item.html.erb
<tr>
		<td>
			<% if !job.is_hidden %>
				招聘中
				<% else %>
				隐藏
				<% end%>
		</td>
		<td><%= link_to(job.title, job_path(job)) %></td>
		<td><%= job.wage_lower_bound %></td>
		<td><%= job.wage_upper_bound %></td>
		<td>
			<% if current_user && current_user == job.user %>
				<%= link_to("Edit", edit_job_path(job), class: "btn btn-sm btn-default")%>
				<%= link_to("Delete", job_path(job),    class: "btn btn-sm btn-default",
										method: :delete, data: { confirm: "Are you sure?" } )%>
			<% end %>
		</td>
		<td><%= job.created_at %></td>
</tr>

app/views/admin/jobs/_jobs_table.html.erb
<tr>
	<td>
		<% if job.is_hidden %>
			<i class="fa fa-lock" aria-hidden="true"></i>
		<% else %>
			<i class="fa fa-globe" aria-hidden="true"></i>
		<% end %>
		<%= link_to(job.title, admin_job_path(job)) %>
	</td>
	<td><%= job.updated_at %></td>
	<td><%= link_to("Edit", edit_admin_job_path(job), class: "btn btn-primary btn-sm") %> |
	<%= link_to("Delete", admin_job_path(job), class: "btn btn-primary btn-sm", method: :delete, data: {confirm: "Are you sure"}) %>
	</td>
</tr>

app/views/admin/jobs/_sidebar.html.erb
<div class="col-md-2 sidebar">
	<ul class="nav nav-pills nav-stacked">
  		  <li role="presentation"><a href="#">Overview</a></li>
		  <li role="presentation"><a href="#">Profile</a></li>
		  <li role="presentation"><a href="#">Messages</a></li>
	</ul>
	<form>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default btn-sm">Submit</button>
     </form>
</div>

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/edit.htnl.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/eidt.html.erb
<h1> Edit a job</h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪資下限" %>
<%= f.input :wage_upper_bound, :label => "薪資上限" %>
<%= f.input :contact_email %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("Add a Job", new_admin_job_path, :class => "btn btn-default") %>
</div>

<br><br>
<table class="table table-boldered">
  <% @jobs.each do |job| %>
  <tr>
    <td>
      <% if job.is_hidden %>
      (Hidden)
      <% else %>
      (Public)
      <% end %>
      <%= link_to(job.title, admin_job_path(job)) %>
    </td>
    <td>
      <%= link_to("Edit", edit_admin_job_path(job)) %> |
      <%= link_to("Destroy", admin_job_path(job), :method => :delete, :data => {:confirm => "Are you sure?"}) %>
    </td>
    <td>
      <%= job.created_at %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1> Add a Job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit" %>

<% end %>

app/views/admin/jobs/open.html.erb
<h1>hshshshs</h1>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>
  <%= @job.wage_lower_bound %>
  <br>
  <%= @job.wage_lower_bound %>
  <br>
  <%= @job.contact_email %>
</p>